core/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = 'core'

urlpatterns = [
    path('susmap/all/', views.list_all_susmap),
    path('card/user/', views.list_user),
    path('login/', views.login_user),
    path('card/detail/<id>/', views.card_detail),
    path('card/forms/', views.forms),
    path('card/forms/submit', views.set_cardform),
    path('login/submit', views.submit_login),
    path('logout/', views.logout_user),
    path('', RedirectView.as_view(url="susmap/all/")),
    path('unidades/listar', views.unidades_listar, name='unidades-listar'),
    path('atendimento/finalizar', views.finalizar_atendimento, name='finalizar-atendimento'),
    path('atendimento/listar', views.fila_atendimento, name='fila-atendimento'),
    path('servico/cadastrar/', views.fila_atendimento, name='servico-cadastrar')
]

susmap/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.views.generic import RedirectView
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import settings

#app_name='core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),

]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Card(models.Model):
    city = models.CharField(max_length=100)
    description = models.TextField()
    phone = models.CharField(max_length=11)
    email = models.EmailField()
    beging_date = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(upload_to='card')
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

    class card:
        db_table = 'card'


class Qualificador(models.Model):
    nome = models.CharField(max_length=50)
    sintoma = models.ForeignKey("Sintoma", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

    class card:
        db_table = 'qualificador'

class Sintoma(models.Model):
    nome = models.CharField(max_length=50)
    descricao = models.TextField()

    def __str__(self):
        return str(self.id)

    def __eq__(self, sintoma):
        if (isinstance(sintoma, Sintoma)):
            return self.nome == sintoma.nome
        return False

    class card:
        db_table = 'sintoma'

#Usuário
class Usuario(models.Model):
    nome = models.CharField(max_length=50)
    cpf = models.CharField(max_length=11)
    endereco = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    senha = models.CharField(max_length=10)

#Paciente
class Paciente(models.Model):
    numeroSUS = models.CharField(max_length=10)
    ranking = models.CharField(max_length=300)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
    )

class Atendente(models.Model):
    unidadeAtendimento = models.CharField(max_length=20)
    #unidade = models.ForeignKey("UnidadeSaude", on_delete=models.CASCADE)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
    )

class Administrador(models.Model):
    gerenciamentoAtendentes = models.CharField(max_length=20)

class Atendimento(models.Model):
    status_tipos = ((1,"Andamento"), (2,"Finalizado"))
    paciente = models.ForeignKey("Paciente", on_delete=models.CASCADE)
    unidade = models.ForeignKey("UnidadeSaude", on_delete=models.CASCADE)
    status = models.IntegerField(choices=status_tipos, default=1)


class Endereco(models.Model):
    rua = models.CharField(max_length=200, null=False, blank=False)
    numero = models.IntegerField(null=False, blank=False)
    complemento = models.CharField(max_length=200, null=False, blank=False)
    bairro = models.CharField(max_length=50, null=False, blank=False)
    cidade = models.CharField(max_length=100, null=False, blank=False)
    pais = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.rua

class Servico(models.Model):
    nomeServico = models.CharField(max_length=100)
    descricaoServico = models.CharField(max_length=100)
    sintoma = models.ManyToManyField(Sintoma)

class UnidadeSaude(models.Model):
    nomeUnidadeSaude = models.CharField(max_length=50)
    enderecoUnidade = models.OneToOneField(Endereco, on_delete=models.SET_NULL, null=True)
    servico = models.ManyToManyField(Servico)

class Localizacao(models.Model):
    longitude = models.FloatField()
    latitude = models.FloatField()

templates/atendimento-confirmacao.html
{% extends "model-page.html" %}
{% block content %}
<style>
    .titulo-confirmacao {
    text-align: center;
    font-size: 2em;
    margin-top: 35px;
    color: rgb(187, 21, 21);
    margin-bottom: 50;
}
</style>
<p class="titulo-confirmacao">
    Atendimento Finalizado!
</p>
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="text-align: center;">
            <a href="/susmap/all/" type="button" class="btn btn-link">Voltar ao Menu</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="text-align: center;">
            <a href="/logout/" class="btn btn-link" style="text-align: center;">Finalizar acesso</a>
        </div>
    </div>
</div>
{% endblock %}

templates/card.html
{%extends "model-page.html" %}

{%block content%}
<h1 class="text-center">Detalhes do card</h1>

<div class="container mp-4 mb-4">
    <div class="row">
        <div class="col-sm-4">
            <div style="border-color: blue; border-style: solid; width: 256px; height: 270;">
                <img src="{{ card.photo.url }}" width="250" height="250">
            </div>
        </div>
        <div class="col-sm-8">
            <p>{{card.description}}</p>
            <h4>Contato</h4>
            <p><b>Tel.:</b>{{card.phone}}</p>
            <p><b>Email:</b>{{card.email}}</p>
            {% if request.user == card.user %}
            <a href="#">
                <button type="button" class="btn btn-primary">Alterar</button>
            </a>
            <button type="button" class="btn btn-danger">Excluir</button>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/fila-atendimento.html
{% extends "model-page.html" %}
{% block content %}
<style>
    .titulo-fila-atendimento {
    text-align: center;
    font-size: 2em;
    margin-top: 35px;
    color: rgb(17, 16, 16);
    margin-bottom: 50;
}
</style>
<p class="titulo-fila-atendimento">Fila de atendimento</p>
<div class="container">
    {% for unidade in unidades %}
            <div class="row">
            <div class="col">
                <h5 class=""><b>{{unidade.nomeUnidadeSaude}}</b></h5>
                <p class=""><b>Endereço:</b> {{unidade.enderecoUnidade}}</p>
                <p>Quantidade de atendimentos para esta Unidade: {{unidade.atendimento_set.count}}</p>
                {% for servico in unidade.servico.all %}
                <p>{{servico.nomeServico}}</p>
                {% endfor%}
            </div><br>
            </div>
    {% endfor %}
</div>
{% endblock %}

templates/inicio.html
<html>
    <head>
        {% block style%} {% endblock %}
        {% include "model-header.html" %}
    </head>

    <body>
        {% block content %} {%endblock%}
        {% if request.user.paciente %}
        <div class="container" style="margin-top: 50px;">
            <div class="row">
                <div class="col-sm-3"></div>
                <div class="col-sm-6 alert alert-primary" role="alert">
                    <p><h5>Seja bem vindo!</h5> Este sistema tem como objetivo lhe informar sobre 
                        as unidades de atendimento que atende as suas necessidades 
                        de acordo com os sintomas informados na aba formulário.
                    </p>
                    <hr>
                    <p class="mb-0">
                        Favor preencher o formulário e seguir para a unidade que melhor lhe atende!
                    </p>
                </div>
            </div>
        </div>
        {% endif %}
        {% include "model-footer.html" %}
    </body>
</html>

templates/list.html
{% extends "model-page.html" %}
{% block style %}
<style>
    .polaroid{
        width: 250px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.2);
        text-align: center;
    }
    .container {
        padding: 10px;
    }
</style>
{%endblock%}
{% block content %}

    <!--{% for p in card %}
       <p>{{ p.city}}</p>
        <p>{{ p.description}}</p>
    {% endfor %}
    -->
    <div class="container mb-4">
        <div class="row">
            {% for p in card%}
           <!-- {%for p in card%}
            <div class="col-sm-4">
                <p>{{p.city}}</p>
            </div>
            {%endfor%}
            -->
            <div class="col-sm-4">
                <a href="/card/detail/{{p.id}}">
                    <div class="polaroid">
                        <img src="{{p.photo.url}}" style="width: 100%; height: 130px;">
                        <di class="container">
                            <p>{{p.city}}</p>
                        </di>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>
{%endblock%}

templates/login.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <title>SUSMAP</title>
</head>

<style>
  .containerPrincipal{
    font-weight: bold;
    padding: 1rem;
    background: cadetblue;
  }
  .card-signin .card-title {
    margin-bottom: 2rem;
    font-weight: 300;
    font-size: 1.5rem;
    padding: 6rem;
  }
   .form-signin {
    font-size: 100%;
    border-radius: 1rem;
    letter-spacing: .1rem;
    padding: 1rem;
    background: rgb(229, 239, 240);
}
</style>

<body class="d-flex flex-column containerPrincipal">
  <div class="sidenav">
         <div class="login-main-text">
            <h1 class="card-title text-center">SUSMAP<h1> 
         </div>
   </div>
      <div class="main card-signin">
         <div class="col-md-6 col-sm-12 container">
            <div class="login-form">
               <form class="form-signin" action="submit", method="POST">{% csrf_token %}
                  <div class="form-group">
                     <label>Usuário</label>
                     <input type="text" class="form-control" placeholder="Usuário" name="username">
                  </div>
                  <div class="form-group">
                     <label>Senha</label>
                     <input type="password" class="form-control" placeholder="Senha" id="password" name="password">
                  </div>
                  <div>
                    {% for message in messages %}
                    <div class="alert alert-danger">
                      <strong>Error!</strong>{{message}}
                    </div>
                    {% endfor %}
                    <div class="custom-control custom-checkbox mb-3">
                     <input type="checkbox" class="custom-control-input" id="customCheck1">
                     <label class="custom-control-label" for="customCheck1">Lembrar senha</label>
                   </div>
                   <p>
                     <a routerLink="/cadastro">Cadastre-se</a>
                   </p>
                    <button type="submit" class="btn btn-success">Entrar</button>
                  </div>                
               </form>
            </div>
         </div>
      </div>
</body>
</html>

templates/model-footer.html
<div class="text-center" style="background-image: linear-gradient(cadetblue, rgba(7, 14, 114, 0.904)); color: white;
                                                     width: 100%; position: absolute;">
    <p>SUSMAP</p>
</div>

templates/model-formulario.html
{%extends "model-page.html" %}

{% block content %}
<style>
.titulo {
    text-align: center;
    font-size: 2em;
    margin-top: 35px;
    color: rgb(21, 121, 187);
}

.box-qualificadores {
    width: 100%;
    max-width: 1140px;
    margin: 0 auto;
    display: flex;
    flex-wrap: wrap;
    padding-top: 45px;
}

.qualificador {
    width: calc(33.33% - 4px );
    max-width: 100%;
    padding: 30px 15px;
    margin: 2px;
    transition: 1s;
}

.butao1{
    margin-top: 50;
}

.campo-sintomas{
    margin-top: 30px;
}

</style>
<form action="{% url 'core:unidades-listar'%}" method="post">{% csrf_token %}
<h1 class="titulo">Selecione um dos qualificadores</h1>

<section class="box-qualificadore">
    <div class="container">
        {% for message in messages %}
        <div class="alert alert-danger">
            <strong>Error!</strong>{{message}}
        </div>
        {% endfor %}
    </div>
    <div class="container campo-sintomas">
        {% for s in sintoma %}
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-3">
                <h5>{{s.nome}}</h5>
            </div>
            <div class="col-md-3">   
                <select class="form-control" name="{{s.nome}}" >
                    <option value="">Selecione</option>
                {% for q in s.qualificador_set.all %}
                    <option value="{{q.nome}}">{{q.nome}}</option>
                {% endfor %}
                </select>
           </div>
           <div class="col-md-3"></div>
        </div>
       {% endfor %}
    </div>
    <div class="container">
        <div class="row">
            <div class="butao1">
                <a href="#">
                    <button type="submit" class="btn btn-primary">Próximo</button>
                   </a>
            </div>
        </div>
    </div>  
</section>
</form>
{% endblock %}

templates/model-header.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<title>SUSMAP</title>
<stayle>
    <style>
        #menu a{
            color: white;
        }
        .header{
            background-color: cadetblue;
            color: white;
            background-image: linear-gradient(cadetblue, rgba(7, 14, 114, 0.904));
        }
        .logout a{
            color: white;
        }
        .navbar{
            margin-top: 50;
        }
    </style>
</stayle>

<div class="header text-center">
    <h1>SUSMAP</h1>
    <nav class="navbar navbar-expand-lg menu-inicial">
        <div class="collapse navbar-collapse" id="menu">
          <ul class="navbar-nav">
            {% if request.user.paciente %}
            <li>
                <a class="nav-link" href="/susmap/all/">Início</a>
            </li>
            {% endif %}
            {% if request.user.paciente %}
            <li>
                <a class="nav-link" href="/card/forms">Formulário</a>
            </li>
            {% endif %}
            {% if request.user.atendente %}
            <li>
                <a class="nav-link" href="/servico/cadastrar">Cadastrar Servico</a>
            </li>
            {% endif %}
          </ul>
          <!--<form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Pesquisar">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
          </form>-->
        </div>
        {% if request.user.paciente %}
        <div class="mr-4" style="color: rgb(255, 255, 255)">
            <h4>Olá, {{user.paciente.user}}!</h4>
        </div>
        {% endif %}
        {% if request.user.atendente %}
        <div class="mr-4" style="color: rgb(255, 255, 255)">
            <h4>Olá, {{user.atendente.user}}!</h4>
        </div>
        {% endif %}
        <div class="text-right mr-4 logout">
            <a href="/logout/">Sair</a>
        </div>
      </nav>
</div>

templates/model-page.html
<html>
    <head>
        {% block style%} {% endblock %}
        {% include "model-header.html" %}
    </head>

    <body>
        {% block content %} {%endblock%}
        {% include "model-footer.html" %}
    </body>
</html>

templates/register_unid.html
{%extends "model-page.html" %}

{% block content %}
<h1 class="text-center">Registre sua Unidade de Saude</h1>
<form enctype="multipart/form-data" action="{% url 'core:servico/cadastrar'%}", method="POST">{% csrf_token %}
<div class="container">
    <div class="form-group">
        <label for="email">E-mail</label>
        <input class="form-control" name="email" type="text">
    </div>
    <div class="form-group">
        <label for="phone">Telefone:</label>
        <input class="form-control" name="phone" type="number">
    </div>
    <div class="form-group">
        <label for="city">Cidade:</label>
        <input class="form-control" name="cuty" type="text">
    </div>
    <div class="form-group">
        <label for="description">Decrição:</label>
        <textarea class="form-control" rows="5" name="description"></textarea>
    </div>
    <div class="form-group">
        <input class="form-control-file border" name="file" type="file" accept="image/*">
    </div>
    <button class="btn btn-primary" type="submit">
        Cadastrar
    </button>
</form>
</div>
{% endblock %}

templates/tela-confirmacao.html
{% extends "model-page.html" %}
{% block content %}
<style>
    .titulo-confirmacao {
    text-align: center;
    font-size: 2em;
    margin-top: 35px;
    color: rgb(187, 21, 21);
    margin-bottom: 50;
}
</style>
<p class="titulo-unidades titulo-confirmacao">
    Atendimento Finalizado!
</p>
<div class="container">
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="text-align: center;">
            <button type="button" class="btn btn-link">Voltar ao Menu</button>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="text-align: center;">
            <button type="button" class="btn btn-link" style="text-align: center;">Finalizar acesso</button>
        </div>
    </div>
</div>
{% endblock %}

templates/unidades-listar.html
{% extends "model-page.html" %}
{% block content %}
<style>
    .titulo-unidades {
    text-align: center;
    font-size: 2em;
    margin-top: 35px;
    color: rgb(21, 121, 187);
}
</style>
<p class="titulo-unidades" style="margin-bottom: 50;">
    As unidades de atendimento que atende as suas necessidades estão listadas abaixo:
</p>
<form action="{% url 'core:finalizar-atendimento'%}" method="POST">{% csrf_token %}
    <section>
        <div class="container">
            {% for message in messages %}
            <div class="alert alert-danger">
                <strong>Error!</strong>{{message}}
            </div>
            {% endfor %}
        </div>
        <div class="container">
            {% for unidade in unidades %}
            <div class="row">
            <div class="col">
                <label class="form-check-label">
                    <input type="radio" class="form-check-input" value="{{unidade.id}}" name="unidade_id"
                    {% if forloop.first %} checked {% endif %}
                    >
                </label>
                <h5 class=""><b>{{unidade.nomeUnidadeSaude}}</b></h5>
                <p class=""><b>Endereço:</b> {{unidade.enderecoUnidade}}</p>
                <p><b>Horário de funcionamento:</b></p>
                <p><b>Tel.:</b></p>
            </div><br>
            </div>
            {% endfor %}
            <div class="row" style="margin-top: 90px;"> 
                <div class="col-sm-3">
                    <a href="/card/forms" class="btn btn-primary botao-anterior" type="submit">Voltar</a>
                </div>
                <div class="col-sm-3"></div>
                <div class="col-sm-3"></div>
                <div class="col-sm-3">
                    <button class="btn btn-primary botao-proximo" type="submit">Próximo</button>
                </div>
            </div>
        </div>
    </section>
</form>
{% endblock %}